### ISSUE TITLE
getting issue while running the emulation example

### ISSUE THREAD

**Issue by psumesh** [themperek/ORConf23#1]
Hi @themperek 
I'm currently working with your example code, and I encountered an issue when running the following command:
`openFPGALoader -b arty fw/build/tdc_emu_top.bit`

The error I received is:
```
unable to open ftdi device: -3 (device not found)
JTAG init failed with: unable to open ftdi device
```
Could you please provide guidance on what might be causing this issue or how I might resolve it?

**Comment by themperek** [comment]
This command will program FPGA ([arty](https://www.xilinx.com/products/boards-and-kits/arty.html)).  Do you have one?

**Comment by psumesh** [comment]
I will plug and dump in arty😊
